### ISSUE TITLE
Unable to run findbugs on newer maven versions

### ISSUE THREAD

**Issue by hexedpackets** [spotify/ffwd#154]
Findbugs is broken with newer versions of maven. Since the project has been abandoned for quite a while there's pretty much no chance of it being fixed. We should switch to a different library.

**Comment by dmichel1** [comment]
I tried using spotbugs on another project and it was really broken for Java 11. I don't think spotbugs is good choice as of now.

https://github.com/spotbugs/spotbugs/issues/756
https://github.com/spotbugs/spotbugs/issues/811
