### ISSUE TITLE
Implement resource identifier support in json module

### ISSUE THREAD

**Issue by sjoeboo** [spotify/ffwd#204]
Currently only the http module supports metric input with resource identifiers, it was never added to the json input:

https://github.com/spotify/ffwd/blob/049aa48dc3185542fe27da10f34345d7a7bd85d2/modules/json/src/main/java/com/spotify/ffwd/json/JsonObjectMapperDecoder.java#L111

Json module should be updated to handle metrics with resource identifiers

Bonus: all input modules should handle resource identifiers to standardize it across inputs.

**Comment by sjoeboo** [comment]
missing in protbuf as well:

https://github.com/spotify/ffwd/blob/049aa48dc3185542fe27da10f34345d7a7bd85d2/modules/protobuf/src/main/java/com/spotify/ffwd/protobuf/ProtobufDecoder.java#L124

**Comment by smstone** [comment]
This is available in ffwd 0.6.6, closing!
