### ISSUE TITLE
instrumentation support

### ISSUE THREAD

**Issue by udoprog** [spotify/ffwd#4]
The following instrumentation hooks are required:
- On a per input plugin basis.
  - Measure errors.
  - Measure dropped events/metrics.
  - Measure failed events/metrics.
  - Measure received events/metrics.
- On an application basis.
  - Measure event rates.
  - Measure metric rates.
  - Measure failure rates.
- On a per output plugin basis.
  - Measure sent events/metrics.
  - Measure dropped events/metrics.
  - Measure queue time in ms for events/messages.
  - Measure queue size and rate-of-growth for events/messages.

**Comment by udoprog** [comment]
This has in part been addressed in b375c2211fb76e5b121bf007837d86902065d4c4 and a few follow up commits.

In master we currently have basic scaffolding for reporting metrics related to;
* Sent events/metrics
* Received events/metrics
* Dropped by output plugins

**Note**: Only FlushingPluginSink currently reports dropped metrics.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
