### ISSUE TITLE
ffwd issues with the agent

### ISSUE THREAD

**Issue by Azim0313** [spotify/ffwd#91]
05:35:25.755 [main] ERROR com.spotify.ffwd.FastForwardAgent - Error in agent, exiting
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by dmichel1** [comment]
hi @Azim0313 

What version of ffwd are you using and can you share the config as well? It will make it easier to troubleshoot.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
